/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefreshTokenRefreshTokenRequest as TemplateApiEndpointsUsersRefreshTokenRefreshTokenRequest } from '../../models/Template/API/Endpoints/Users/refresh-token-refresh-token-request';
import { LoginResponse as TemplateApplicationUsersCommandsLoginLoginResponse } from '../../models/Template/Application/Users/Commands/Login/login-response';

export interface RefreshToken$Params {
      body: TemplateApiEndpointsUsersRefreshTokenRefreshTokenRequest
}

export function refreshToken(http: HttpClient, rootUrl: string, params: RefreshToken$Params, context?: HttpContext): Observable<StrictHttpResponse<TemplateApplicationUsersCommandsLoginLoginResponse>> {
  const rb = new RequestBuilder(rootUrl, refreshToken.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TemplateApplicationUsersCommandsLoginLoginResponse>;
    })
  );
}

refreshToken.PATH = '/users/refresh-token';
