/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Void as SystemVoid } from '../../models/System/void';

export interface VerifyEmail$Params {
  token: string;
}

export function verifyEmail(http: HttpClient, rootUrl: string, params: VerifyEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<SystemVoid>> {
  const rb = new RequestBuilder(rootUrl, verifyEmail.PATH, 'get');
  if (params) {
    rb.query('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SystemVoid>;
    })
  );
}

verifyEmail.PATH = '/users/verify-email';
