/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TickerType as TickerQUtilitiesEnumsTickerType } from '../../models/TickerQ/Utilities/Enums/ticker-type';

export interface ApiTickerRequestIdGet$Params {
  tickerId?: string;
  tickerType?: TickerQUtilitiesEnumsTickerType;
}

export function apiTickerRequestIdGet(http: HttpClient, rootUrl: string, params?: ApiTickerRequestIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiTickerRequestIdGet.PATH, 'get');
  if (params) {
    rb.query('tickerId', params.tickerId, {});
    rb.query('tickerType', params.tickerType, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiTickerRequestIdGet.PATH = '/api/ticker-request/:id';
