/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SetBatchParentRequest as TickerQDashboardRequestsSetBatchParentRequest } from '../../models/TickerQ/Dashboard/Requests/set-batch-parent-request';

export interface ApiTimeTickersSetBatchParentPost$Params {
      body?: TickerQDashboardRequestsSetBatchParentRequest
}

export function apiTimeTickersSetBatchParentPost(http: HttpClient, rootUrl: string, params?: ApiTimeTickersSetBatchParentPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiTimeTickersSetBatchParentPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiTimeTickersSetBatchParentPost.PATH = '/api/time-tickers/set-batch-parent';
