/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiCronTickerOccurrencesCronTickerIdGet$Params {
  cronTickerId?: string;
}

export function apiCronTickerOccurrencesCronTickerIdGet(http: HttpClient, rootUrl: string, params?: ApiCronTickerOccurrencesCronTickerIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiCronTickerOccurrencesCronTickerIdGet.PATH, 'get');
  if (params) {
    rb.query('cronTickerId', params.cronTickerId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiCronTickerOccurrencesCronTickerIdGet.PATH = '/api/cron-ticker-occurrences/:cronTickerId';
