/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Permission as TemplateDomainUsersPermission } from '../../../../models/Template/Domain/Users/permission';
import { User as TemplateDomainUsersUser } from '../../../../models/Template/Domain/Users/user';
export interface Role {
  id?: number;
  name?: string;
  permissions?: Array<TemplateDomainUsersPermission>;
  users?: Array<TemplateDomainUsersUser>;
}
