/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role as TemplateDomainUsersRole } from '../../../../models/Template/Domain/Users/role';
import { IDomainEvent as TemplateSharedKernelDomainIDomainEvent } from '../../../../models/Template/SharedKernel/Domain/i-domain-event';
export interface User {
  domainEvents?: Array<TemplateSharedKernelDomainIDomainEvent>;
  email?: string;
  firstName?: string;
  id?: string;
  lastName?: string;
  passwordHash?: string;
  role?: TemplateDomainUsersRole;
}
