/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BatchRunCondition as TickerQUtilitiesEnumsBatchRunCondition } from '../../../../models/TickerQ/Utilities/Enums/batch-run-condition';
export interface SetBatchParentRequest {
  batchRunCondition?: TickerQUtilitiesEnumsBatchRunCondition;
  parentId?: string;
  targetId?: string;
}
